use_frameworks!

platform :ios, '9.0'

target 'YJSStockKeyboardView_Example' do
  pod 'YJSStockKeyboardView', :path => '../'

  target 'YJSStockKeyboardView_Tests' do
    inherit! :search_paths

    
  end
end
